language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: EmbeddingIntentClassifier
  - name: DucklingHTTPExtractor
    dimensions:
      - time

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy 
